block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
  "clippy (1.55)",
  "clippy (1.63)",
  "clippy (1.63, std)",
  "rustfmt",
  "test (1.55)",
  "test (1.63)",
  "test (1.63, std)",
]
