# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2021-08-18"
components = [ "rust-src", "rustfmt" ]
targets = [
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabi",
    "riscv32imc-unknown-none-elf",
    "riscv32imac-unknown-none-elf",
    "avr-specs/avr-atmpeg328p.json",
]
